import multiprocessing as mp
import argparse as ap
import sys


CPU_COUNT = mp.cpu_count()


def argument_parser():
    argparser = ap.ArgumentParser(description="This script parses fastq files into average PHRED scores over"
                                              "each position",
                                  usage="python3 Opdracht1.py -n <aantal_cpus>")
    argparser.add_argument("-n", type=int, metavar='',  required=True,
                           help="The amount of cores to use when running the application.")
    argparser.add_argument("-o", type=str, metavar='', required=False)

    argparser.add_argument("fastq_files", action="store", type=ap.FileType('r'), nargs='+',
                           help="At least one Illumina fastq format file to process")

    return argparser.parse_args()


def average(lines, start, stop, output_queue):
    # total for each position
    totals = {}
    # number of positions
    length = stop - start + 1
    # iteration counter
    while start < stop:
        # get a line
        line = lines[start]
        # loop through scores in line
        for i, score in enumerate(line):
            if i in totals:
                # at to totals
                totals[i] += ord(score) - 33
            else:
                # initiate position
                totals[i] = ord(score) - 33
        start += 1

    averages = [round(totals[pos] / length, 2) for pos in totals]
    output_queue.put(averages)


def read_file(file_name):
    """
    Opens a file with the given file name and reads all phred score lines into a list (so every 4th line of the file).
    :param file_name:
    :return lines: The phred score lines in list form
    :return: number of lines in the list
    """
    # get lines
    with open(file_name, 'r') as file:
        lines = []
        check = 0
        for line in file:
            check += 1
            if check % 4 == 0:
                lines.append(line.strip())

    return lines, check // 4


def multiprocess(lines, numb_of_lines, cores=CPU_COUNT):
    """
    This functions handles the multi processing part of the program. It assigns a part of the lines list to each process
    and then starts the multiprocessing.
    :param lines: a list containing the phred score lines of a fastq file.
    :param numb_of_lines: the length of the lines list (I basically only did this to avoid using the len function).
    :param cores: the amount of cores to use during multiprocessing/the number of processes, defaults to maximum
                    available cores.
    :return output_queue: A queue of output lists that were created by the average function during multiprocessing.
    """
    # start new que and empty process list
    output_queue = mp.Queue()
    processes = []
    # calculate how many lines each process will have to take to evenly divide all of them
    lines_per_process = numb_of_lines // cores
    # save the amount of leftover lines
    leftover = numb_of_lines % cores
    # get start and stop index for all processes
    start_stops = [[lines_per_process * process, lines_per_process * (process + 1)]
                   for process in range(cores)]
    # assign the last lines to the last process
    start_stops[-1][1] += leftover

    # create processes
    for position in start_stops:
        # new process
        new_p = mp.Process(target=average, args=(lines, position[0], position[1], output_queue))
        processes.append(new_p)
        # start process
        new_p.start()

    # join
    for p in processes:
        p.join()

    return output_queue


def calculate_final_average(queue):
    """
    calculate the final averages after the multi processing has finished
    :param queue: The ouput queue generated by the multiprocessing function
    :return results: The final averages of each position, the end result of the script
    """
    # empty lists
    results = []
    # the inverse of the que size, this done purely because multiplying is faster than dividing, here we divide once
    # so that in the loop we only need to multiply by this inverse. completely unnecessary step.
    inv_queue_length = 1 / queue.qsize()

    while not queue.empty():
        # while queue is not empty, get new lines from the que
        line = queue.get()
        for j in range(len(line)):
            # for every position in the line
            if not results:
                results = line
            else:
                # calculate the average
                results[j] += line[j] * inv_queue_length
    return results


def main():
    # Get args
    args = argument_parser()
    n_cpus = args.n
    file_names = args.fastq_files
    # Get lines
    lines, numb_of_lines = read_file(file_names)
    # Multiprocess
    averages = multiprocess(lines, numb_of_lines, n_cpus)
    # Finalize
    print(calculate_final_average(averages))
    return 0


if __name__ == "__main__":
    sys.exit(main())
